name: Build & release
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  release:
    name: Build & release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - name: Cache next js build output
        uses: actions/cache@v2
        with:
          path: |
            .next/cache
            node_modules/.cache
          key: next-cache
      - name: Install dependencies
        run: npm ci --prefer-offline
        env:
          HUSKY: 0
      - name: Build app
        run: npm run build
        env:
          MAD_DB_DATABASE_NAME: ${{ secrets.DB_DATABASE_NAME }}
          MAD_DB_HOST: ${{ secrets.DB_HOST }}
          MAD_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MAD_DB_USER: ${{ secrets.DB_USER }}
          LEADERBOARD_DB_DATABASE_NAME: ${{ secrets.DB_DATABASE_NAME }}
          LEADERBOARD_DB_HOST: ${{ secrets.DB_HOST }}
          LEADERBOARD_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          LEADERBOARD_DB_USER: ${{ secrets.DB_USER }}
      # Send webpack stats and build information to RelativeCI
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@v1.1.0
        with:
          webpackStatsFile: ./.next/stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
      - name: Lint
        run: npm run lint
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
        run: npx semantic-release
